# yamllint disable rule:line-length
---
name: slack-bot

description: |
  Post message to slack using slack-bot API. Assumes $SLACK_BOT_TOKEN is present.

  Parameters:
    channel: post message to this slack channel
    message: message to imbed ni default post format
    custom-message: override complete post-bot json body
    include-link: include link to workflow run
    include-tag: include version tag in message

inputs:

  channel:
    description: slack chanel
    required: true

  message:
    description: message for default post format
    required: false
    default: "empty message"

  custom-message:
    description: override complete post-bot json body. Ignores $input.message.
    required: false
    default: ""

  include-link:
    description: include link to workflow run. Default is false.
    required: false
    default: "false"

  include-tag:
    description: include version tag in message. Default is false.
    required: false
    default: "false"

runs:
  using: "composite"

  steps:

    - name: slack-bot message
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -eo pipefail

        WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

        if [[ "${{ inputs.include-tag }}" == "false" ]]; then
          msg="${{ inputs.message }}"
        else
          msg="${{ inputs.message }} ${{ github.ref_name }}"
        fi

        if [[ "${{ inputs.custom-message }}" != "" ]]; then
          json="${{ inputs.custom-message }}"
        else
          if [[ "${{ inputs.include-link }}" == "false" ]]; then
            json=$(cat <<EOF
        {"channel": "${{ inputs.channel }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"$msg"}}]}
        EOF
        )
          else
            json=$(cat <<EOF
        {"channel": "${{ inputs.channel }}","blocks": [{"type": "section","text": {"type": "mrkdwn","text": "$msg"}},{"type": "divider"},{"type": "actions","elements": [{"type": "button","text": {"type": "plain_text","text": "go to pipeline","emoji": true},"url": "${WORKFLOW_URL}"}]}]}
        EOF
        )
          fi
        fi

        echo $json
        curl -H "Content-type: application/json; charset=utf-8" \
              --data "$json" \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -X POST https://slack.com/api/chat.postMessage
