# yamllint disable rule:line-length
---
name: gren

description: generate release notes using gren

inputs:

  gren-additional-args:
    description: additional custom command line flags
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - name: generate release notes using gren
      shell: bash
      env:
        GREN_ADDITIONAL_ARGS: ${{ inputs.gren-additional-args }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        #!/usr/bin/env bash
        set -eo pipefail
        gren release -t "$REF_NAME" "$GREN_ADDITIONAL_ARGS"
